### ISSUE TITLE
setup.py raises UnicodeDecodeError if LANG is unset under py3k

### ISSUE THREAD

**Issue by neirbowj** [Thibauth/tabletext#1]
The `README.rst` file is UTF-8 encoded. `setup.py` relies on `open` to guess the encoding, which it does by using `locale.getpreferredencoding()`. When LANG is unset, python may end up guessing conservatively and choose US-ASCII.

For example, on FreeBSD 10.3 with python3.4:

```
$ echo $LANG
$ python3 -c "import locale; print(locale.getpreferredencoding());"
US-ASCII
$ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    + open("CHANGELOG.rst").read(),
  File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1323: ordinal not in range(128)
```

There may be some other mechanism that I don't understand yet, because I can produce the same trace on OS X 10.10.5 when `locale.getpreferredencoding()` guesses UTF-8.

```
$ echo $LANG

$ python3 -c "import locale; print(locale.getpreferredencoding());"
UTF-8
$ python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    + open("CHANGELOG.rst").read(),
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1323: ordinal not in range(128)
```

**Comment by Athanaseus** [comment]
I'm still getting the same error when installing the version on **pypi** using *pip3*.
Making any release soon?
